/** Static interview Q&A content for SEO pages. Role-specific + shared UAE questions. */
export type QA = { q: string; a: string };

/** 12 questions every UAE candidate should prepare, regardless of role. */
export const GENERIC_UAE: QA[] = [
  { q: 'Tell me about yourself.', a: 'Give a 60–90 second summary: your current role, key achievements with numbers, relevant UAE experience, and why this role fits your next step. Keep it professional and tailored to the job.' },
  { q: 'Why do you want to work in the UAE?', a: 'Mention concrete reasons: career growth, the multicultural environment, tax-free salary, and the company\'s reputation. Avoid generic answers — link it to your long-term plan.' },
  { q: 'What is your current visa status?', a: 'Be honest and specific (employment visa, visit visa, cancelled visa, golden/blue visa, or sponsored). Employers need this to plan onboarding and any visa transfer or new sponsorship.' },
  { q: 'What is your notice period and availability?', a: 'State your contractual notice (commonly 30 days in the UAE) and your earliest start date. If you are on a visit visa, say you can join immediately.' },
  { q: 'What are your salary expectations?', a: 'Give a researched monthly AED range, noting whether it is all-inclusive or basic + allowances. Reference market data and stay flexible on the package, not just base pay.' },
  { q: 'Why are you leaving your current job?', a: 'Stay positive — focus on seeking growth, new challenges or a better fit. Never criticise a previous employer; UAE hiring managers value professionalism and discretion.' },
  { q: 'Describe a challenge you faced and how you handled it.', a: 'Use the STAR method (Situation, Task, Action, Result). Pick a real example with a measurable outcome and emphasise what you personally did.' },
  { q: 'How do you work in a multicultural team?', a: 'The UAE workforce is highly diverse. Show cultural awareness, adaptability, clear communication, and respect for different working styles and religious practices (e.g. prayer times, Ramadan hours).' },
  { q: 'Where do you see yourself in five years?', a: 'Show ambition aligned with the company. Mention progression, deeper expertise, or leadership — signal you intend to stay and grow rather than use the role as a stop-gap.' },
  { q: 'What are your strengths and weaknesses?', a: 'Pick strengths relevant to the job with evidence. For weaknesses, choose a genuine one and describe how you are actively improving it.' },
  { q: 'Do you have any questions for us?', a: 'Always say yes. Ask about team structure, success metrics for the role, growth path, or the package details (visa, insurance, allowances). It signals genuine interest.' },
  { q: 'Are you willing to relocate within the UAE or travel?', a: 'If true, say yes and show flexibility across emirates. Clarify any constraints honestly so expectations are aligned from the start.' },
];

/** 8 role-specific questions per category. */
export const ROLE_QUESTIONS: Record<string, QA[]> = {
  it: [
    { q: 'Which programming languages and frameworks are you strongest in?', a: 'Name your core stack with depth, then adjacent tools. Tie each to a shipped project and your specific contribution.' },
    { q: 'How do you ensure code quality and security?', a: 'Mention code reviews, automated tests, CI/CD, linting, and secure practices (input validation, secrets management, OWASP awareness).' },
    { q: 'Describe a production incident you resolved.', a: 'Walk through detection, diagnosis, fix, and the prevention you put in place afterwards (monitoring, alerts, post-mortem).' },
    { q: 'How do you stay current with technology?', a: 'Reference documentation, communities, side projects and certifications relevant to UAE employers (AWS, Azure, security certs).' },
    { q: 'Explain how you design a scalable system.', a: 'Cover load balancing, caching, database choices, statelessness and observability. Use a real example with traffic numbers if possible.' },
    { q: 'How do you work with non-technical stakeholders?', a: 'Show you translate technical trade-offs into business impact and timelines, and manage expectations clearly.' },
    { q: 'What is your experience with cloud and DevOps?', a: 'Detail cloud providers, containers, IaC, and pipelines. UAE firms increasingly expect cloud-native delivery.' },
    { q: 'How do you handle tight deadlines without sacrificing quality?', a: 'Talk about scoping an MVP, prioritising, communicating risk early, and protecting critical paths with tests.' },
  ],
  healthcare: [
    { q: 'Do you hold a DHA, HAAD/DoH, MOH or DHCC licence?', a: 'State your exact UAE licensing status and eligibility. If not yet licensed, explain where you are in the Dataflow/exam process.' },
    { q: 'How do you ensure patient safety and infection control?', a: 'Reference protocols, hand hygiene, documentation, and adherence to JCI/local standards.' },
    { q: 'Describe handling a medical emergency.', a: 'Use STAR: triage, action, teamwork, and outcome. Emphasise calm decision-making under pressure.' },
    { q: 'How do you communicate with patients from different cultures?', a: 'Show empathy, use of interpreters, and respect for cultural and religious sensitivities common in the UAE.' },
    { q: 'How do you maintain accurate patient records?', a: 'Mention EMR systems, confidentiality (data protection), and timely, precise documentation.' },
    { q: 'How do you handle a disagreement with a physician or colleague?', a: 'Show professionalism, patient-first focus, and escalation through proper channels.' },
    { q: 'What is your experience with the speciality this role requires?', a: 'Give caseload numbers, procedures, and outcomes specific to the speciality.' },
    { q: 'How do you keep your clinical knowledge up to date?', a: 'Reference CME/CPD hours, journals, and certifications recognised by UAE regulators.' },
  ],
  finance: [
    { q: 'Are you familiar with UAE VAT and corporate tax?', a: 'Explain your hands-on experience with 5% VAT filing and the new 9% corporate tax, plus FTA compliance.' },
    { q: 'Which accounting standards and software have you used?', a: 'Mention IFRS and tools like SAP, Oracle, QuickBooks, Zoho or Tally used in the UAE market.' },
    { q: 'How do you ensure accuracy in financial reporting?', a: 'Reconciliations, controls, reviews, and audit trails. Give an example of catching a material error.' },
    { q: 'Describe a time you improved a financial process.', a: 'Use STAR with a measurable result — time saved, cost reduced, or accuracy improved.' },
    { q: 'How do you handle month-end and year-end close?', a: 'Walk through your checklist, deadlines, accruals, and coordination with auditors.' },
    { q: 'What is your experience with budgeting and forecasting?', a: 'Detail models built, variance analysis, and how you presented insights to management.' },
    { q: 'How do you maintain confidentiality of financial data?', a: 'Show awareness of access controls, segregation of duties, and professional ethics.' },
    { q: 'How do you work under audit and regulatory pressure?', a: 'Emphasise organisation, documentation, and calm, accurate responses to auditor queries.' },
  ],
  sales: [
    { q: 'Walk me through your sales process.', a: 'Cover prospecting, qualifying, needs analysis, proposal, objection handling, and closing — with a real UAE example.' },
    { q: 'How do you hit and exceed targets?', a: 'Quantify past achievement (% of quota), pipeline discipline, and follow-up cadence.' },
    { q: 'How do you handle rejection?', a: 'Show resilience, learning from lost deals, and maintaining momentum.' },
    { q: 'How do you build relationships in the UAE market?', a: 'Mention trust, in-person meetings, cultural rapport, and long-term account nurturing.' },
    { q: 'Describe your biggest deal and how you closed it.', a: 'Use STAR with deal size, stakeholders, and the value you articulated.' },
    { q: 'Which CRM tools have you used?', a: 'Name CRMs (Salesforce, HubSpot, Zoho) and how you used data to manage pipeline.' },
    { q: 'How do you handle price objections?', a: 'Reframe around value and ROI, offer options, and avoid discounting as a first response.' },
    { q: 'How do you research a prospect before a meeting?', a: 'Company news, pain points, decision-makers, and a tailored value proposition.' },
  ],
  construction: [
    { q: 'What UAE codes and safety standards are you familiar with?', a: 'Reference local authority approvals, HSE, and OSHAD/DM regulations relevant to your trade.' },
    { q: 'How do you manage site safety?', a: 'Toolbox talks, PPE enforcement, risk assessments, and incident reporting.' },
    { q: 'Describe a project you delivered on time and budget.', a: 'Use STAR with scope, value, and how you controlled cost and schedule.' },
    { q: 'How do you handle delays or material shortages?', a: 'Proactive procurement, rescheduling, and clear client communication.' },
    { q: 'What is your experience reading drawings and BOQs?', a: 'Detail drawing types and quantity take-off experience.' },
    { q: 'How do you coordinate multiple subcontractors?', a: 'Sequencing, daily coordination, and conflict resolution on site.' },
    { q: 'How do you ensure quality control?', a: 'Inspection checklists, snagging, and sign-off procedures.' },
    { q: 'How do you manage labour productivity in UAE heat?', a: 'Midday break compliance, hydration, shift planning, and welfare standards.' },
  ],
  hospitality: [
    { q: 'How do you deliver excellent guest service?', a: 'Anticipate needs, personalise, and recover service failures gracefully. Give a real example.' },
    { q: 'How do you handle a difficult guest complaint?', a: 'Listen, empathise, resolve quickly, and follow up — turning a complaint into loyalty.' },
    { q: 'What is your experience with the brand standards in this role?', a: 'Reference luxury/standard procedures, grooming, and SOPs you have followed.' },
    { q: 'How do you work during peak season and long shifts?', a: 'Show stamina, teamwork, and consistency under pressure.' },
    { q: 'How do you upsell without being pushy?', a: 'Read the guest, recommend genuinely relevant options, and add value.' },
    { q: 'How do you handle cultural and dietary requirements?', a: 'Awareness of halal, allergies, and diverse guest expectations in the UAE.' },
    { q: 'Describe teamwork in a fast-paced F&B or front-office setting.', a: 'Coordination, communication, and covering for colleagues during rushes.' },
    { q: 'How do you maintain hygiene and HACCP standards?', a: 'Detail food safety, cleaning schedules, and compliance checks.' },
  ],
  driving: [
    { q: 'What category of UAE driving licence do you hold?', a: 'State your exact licence (light vehicle, heavy bus, heavy truck) and years held in the UAE.' },
    { q: 'How do you ensure road safety?', a: 'Defensive driving, speed compliance, vehicle checks, and rest breaks.' },
    { q: 'How well do you know UAE routes?', a: 'Describe familiarity with Dubai/Abu Dhabi roads, navigation apps, and Salik/toll handling.' },
    { q: 'How do you handle vehicle maintenance issues?', a: 'Daily inspections, reporting faults early, and keeping logs.' },
    { q: 'How do you deal with traffic fines and Salik?', a: 'Follow company policy, drive compliantly, and report promptly.' },
    { q: 'How do you handle delivery deadlines safely?', a: 'Plan routes, communicate delays, and never compromise safety for speed.' },
    { q: 'How do you interact with customers during deliveries?', a: 'Polite, punctual, and professional handover and proof of delivery.' },
    { q: 'Do you have a clean driving record in the UAE?', a: 'Be honest about points/black points and your safety track record.' },
  ],
  education: [
    { q: 'Are you KHDA/ADEK approved or eligible?', a: 'State your teaching qualifications, attestation status, and regulator approval for the UAE.' },
    { q: 'Describe your classroom management approach.', a: 'Clear expectations, positive reinforcement, and consistency. Give a real example.' },
    { q: 'How do you differentiate instruction?', a: 'Adapt to varied abilities and EAL learners common in UAE classrooms.' },
    { q: 'Which curriculum have you taught?', a: 'Name the curriculum (British, American, IB, MOE) and your subject/grade experience.' },
    { q: 'How do you engage parents?', a: 'Regular communication, reports, and partnership in a multicultural community.' },
    { q: 'How do you use assessment to drive learning?', a: 'Formative checks, data, and targeted intervention.' },
    { q: 'How do you integrate technology in teaching?', a: 'LMS, interactive tools, and blended learning.' },
    { q: 'How do you support student wellbeing?', a: 'Pastoral care, inclusion, and safeguarding awareness.' },
  ],
  admin: [
    { q: 'Which office software are you proficient in?', a: 'MS Office/Google Workspace, scheduling, and any ERP or CRM tools used in UAE offices.' },
    { q: 'How do you prioritise multiple tasks?', a: 'Triage by urgency/importance, use checklists, and communicate timelines.' },
    { q: 'How do you handle confidential information?', a: 'Discretion, access control, and professional ethics.' },
    { q: 'Describe managing a busy executive\'s calendar.', a: 'Coordinate meetings across time zones, anticipate needs, and protect priorities.' },
    { q: 'How do you handle a difficult visitor or caller?', a: 'Stay calm, professional, and solution-focused.' },
    { q: 'How do you maintain accurate records and filing?', a: 'Consistent systems, both digital and physical, with quick retrieval.' },
    { q: 'How do you support a multicultural team?', a: 'Clear communication, cultural sensitivity, and reliability.' },
    { q: 'Describe a process you made more efficient.', a: 'Use STAR with the time or cost you saved.' },
  ],
  manufacturing: [
    { q: 'What is your experience with production targets and KPIs?', a: 'Quantify output, efficiency, and quality metrics you have improved.' },
    { q: 'How do you ensure quality control?', a: 'Inspections, SOPs, and non-conformance handling.' },
    { q: 'How do you maintain workplace safety?', a: 'PPE, machine guarding, LOTO, and incident reporting.' },
    { q: 'What is your experience with lean or 5S?', a: 'Describe waste reduction and continuous improvement you led.' },
    { q: 'How do you handle equipment breakdowns?', a: 'Quick diagnosis, escalation, and preventive maintenance planning.' },
    { q: 'How do you manage a shift team?', a: 'Allocation, communication, and motivation to hit targets.' },
    { q: 'How do you read technical specifications?', a: 'Drawings, tolerances, and adherence to standards.' },
    { q: 'How do you reduce downtime?', a: 'Planned maintenance, spares management, and root-cause analysis.' },
  ],
  security: [
    { q: 'Do you hold a SIRA/PSBD security licence?', a: 'State your UAE security certification and renewal status.' },
    { q: 'How do you handle an emergency or security breach?', a: 'Follow protocol, alert authorities, secure the area, and document.' },
    { q: 'How do you conduct access control and patrols?', a: 'Verification, logs, CCTV monitoring, and reporting anomalies.' },
    { q: 'How do you de-escalate a confrontation?', a: 'Stay calm, communicate clearly, and use force only as a last resort within the law.' },
    { q: 'What is your experience with CCTV and alarm systems?', a: 'Monitoring, incident review, and basic system checks.' },
    { q: 'How do you write an incident report?', a: 'Factual, timed, and complete documentation for investigations.' },
    { q: 'How do you stay alert on long shifts?', a: 'Discipline, patrol routines, and vigilance.' },
    { q: 'How do you handle VIP or crowd situations?', a: 'Planning, positioning, and calm crowd management.' },
  ],
  beauty: [
    { q: 'What treatments and services are you trained in?', a: 'List skills (hair, nails, skincare, spa, makeup) with certifications.' },
    { q: 'How do you maintain hygiene and sanitation?', a: 'Sterilisation, single-use items, and salon health regulations.' },
    { q: 'How do you handle a dissatisfied client?', a: 'Listen, adjust, and recover the experience professionally.' },
    { q: 'How do you build a loyal client base?', a: 'Consistency, personalisation, and rebooking/upselling naturally.' },
    { q: 'How do you keep up with beauty trends?', a: 'Training, social media, and brand education.' },
    { q: 'How do you advise clients on products?', a: 'Assess needs honestly and recommend suitable products.' },
    { q: 'How do you manage time across appointments?', a: 'Punctuality, scheduling, and smooth client flow.' },
    { q: 'How do you work with diverse skin and hair types?', a: 'Knowledge and adaptability for the UAE\'s multicultural clientele.' },
  ],
};

export function questionsFor(role: string): QA[] {
  return [...(ROLE_QUESTIONS[role] ?? []), ...GENERIC_UAE];
}
