/** Emoji for a job by title keyword (first match wins), falling back to category. */

const JOB_EMOJIS: [RegExp, string][] = [
  [/driver|driving|chauffeur|transport|delivery|courier/i, '🚗'],
  [/truck|lorry|tanker|heavy vehicle|forklift/i, '🚛'],
  [/nurse|nursing|midwife/i, '👩‍⚕️'],
  [/doctor|physician|surgeon|medical officer/i, '🩺'],
  [/pharmacist|pharmacy/i, '💊'],
  [/accountant|accounting|bookkeeper/i, '📊'],
  [/finance|financial|investment|banking/i, '💰'],
  [/auditor|audit/i, '🔍'],
  [/software|developer|programmer|coding|engineer.*software/i, '💻'],
  [/web developer|frontend|backend|fullstack/i, '🌐'],
  [/data entry|typist/i, '⌨️'],
  [/it support|technical support|helpdesk/i, '🖥️'],
  [/chef|cook|kitchen|culinary/i, '👨‍🍳'],
  [/waiter|waitress|steward|server/i, '🍽️'],
  [/hotel|hospitality|front desk|concierge/i, '🏨'],
  [/receptionist/i, '📞'],
  [/teacher|tutor|lecturer|instructor|trainer/i, '👨‍🏫'],
  [/principal|headmaster|school/i, '🏫'],
  [/security|guard|bouncer|surveillance/i, '🛡️'],
  [/cleaner|cleaning|housekeeping|janitor/i, '🧹'],
  [/sales|salesman|saleswoman|sales executive/i, '💼'],
  [/marketing|digital marketing|social media/i, '📣'],
  [/graphic designer|designer|creative/i, '🎨'],
  [/architect|civil engineer|structural/i, '🏗️'],
  [/electrician|electrical/i, '⚡'],
  [/plumber|plumbing/i, '🔧'],
  [/mechanic|auto|vehicle|car repair/i, '🔩'],
  [/hr|human resources|recruitment|talent/i, '👥'],
  [/admin|administrator|office|coordinator/i, '📋'],
  [/secretary|personal assistant|pa\b/i, '📝'],
  [/lawyer|legal|advocate|solicitor/i, '⚖️'],
  [/engineer(?!.*software)/i, '⚙️'],
  [/dentist|dental/i, '🦷'],
  [/veterinary|vet\b/i, '🐾'],
  [/pilot|aviation|airline/i, '✈️'],
  [/captain|sailor|marine/i, '⚓'],
  [/photographer|videographer/i, '📸'],
  [/journalist|reporter|editor/i, '📰'],
  [/manager|director|head of/i, '👔'],
  [/ceo|coo|cfo|chief/i, '🏢'],
  [/nanny|babysitter|caregiver/i, '👶'],
  [/beautician|makeup|hair|salon|spa/i, '💄'],
  [/tailor|fashion|garment/i, '🧵'],
  [/baker|pastry|cake/i, '🍰'],
  [/butcher|meat/i, '🥩'],
  [/farmer|agriculture/i, '🌾'],
  [/lab|laboratory|scientist/i, '🔬'],
  [/cashier|teller|billing/i, '💳'],
  [/warehouse|storekeeper|inventory/i, '📦'],
  [/painter|painting/i, '🖌️'],
  [/welder|welding/i, '🔥'],
  [/mason|masonry|bricklayer/i, '🧱'],
  [/carpenter|woodwork/i, '🪚'],
  [/interior|decoration/i, '🛋️'],
  [/real estate|property|agent/i, '🏠'],
  [/insurance/i, '📄'],
  [/travel|tourism|tour guide/i, '🌍'],
  [/supply chain|logistics|procurement/i, '📦'],
  [/quality|qc|qa inspector/i, '✅'],
  [/tea boy|office boy|peon/i, '☕'],
];

const CATEGORY_EMOJIS: Record<string, string> = {
  driving: '🚗',
  healthcare: '🏥',
  finance: '💰',
  it: '💻',
  hospitality: '🍽️',
  construction: '🏗️',
  education: '📚',
  admin: '📋',
  sales: '💼',
  security: '🛡️',
  manufacturing: '🏭',
  beauty: '💄',
  hr: '👥',
};

export function getJobEmoji(title: string, category: string): string {
  const t = title ?? '';
  for (const [re, emoji] of JOB_EMOJIS) {
    if (re.test(t)) return emoji;
  }
  return CATEGORY_EMOJIS[category] ?? '💼';
}
