// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applications">> = Specific
  const handler = {} as typeof import("../../src/app/admin/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/brand-kit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/brand-kit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/brand-kit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/bulk-extract/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bulk-extract">> = Specific
  const handler = {} as typeof import("../../src/app/admin/bulk-extract/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/community-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/community-stories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/community-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/community">> = Specific
  const handler = {} as typeof import("../../src/app/admin/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/admin/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/cta-funnel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cta-funnel">> = Specific
  const handler = {} as typeof import("../../src/app/admin/cta-funnel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/cv-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cv-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/cv-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/feature-flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/feature-flags">> = Specific
  const handler = {} as typeof import("../../src/app/admin/feature-flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/admin/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs/add">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/drafts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs/drafts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/drafts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/admin/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/polls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/polls">> = Specific
  const handler = {} as typeof import("../../src/app/admin/polls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/quick-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/quick-import">> = Specific
  const handler = {} as typeof import("../../src/app/admin/quick-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/salary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/salary">> = Specific
  const handler = {} as typeof import("../../src/app/admin/salary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security">> = Specific
  const handler = {} as typeof import("../../src/app/admin/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/whapi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/whapi">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/whapi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/success-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/success-stories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/success-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tools/bookmarklet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tools/bookmarklet">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tools/bookmarklet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tools/bulk-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tools/bulk-import">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tools/bulk-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/verification-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/verification-queue">> = Specific
  const handler = {} as typeof import("../../src/app/admin/verification-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/verifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/verifications">> = Specific
  const handler = {} as typeof import("../../src/app/admin/verifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/volunteers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/volunteers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/volunteers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/whatsapp-bot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp-bot">> = Specific
  const handler = {} as typeof import("../../src/app/admin/whatsapp-bot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/admin/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/campus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campus">> = Specific
  const handler = {} as typeof import("../../src/app/campus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/career-advisor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/career-advisor">> = Specific
  const handler = {} as typeof import("../../src/app/career-advisor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/category/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/community/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/ama/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/ama/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/community/ama/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/ama/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/ama">> = Specific
  const handler = {} as typeof import("../../src/app/community/ama/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/become-mentor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/become-mentor">> = Specific
  const handler = {} as typeof import("../../src/app/community/become-mentor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/events/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/events/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/community/events/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/events">> = Specific
  const handler = {} as typeof import("../../src/app/community/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/community/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/mentors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/mentors">> = Specific
  const handler = {} as typeof import("../../src/app/community/mentors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../src/app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/profession/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/profession/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/community/profession/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/qa/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/qa/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/community/qa/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/qa">> = Specific
  const handler = {} as typeof import("../../src/app/community/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/volunteers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/volunteers">> = Specific
  const handler = {} as typeof import("../../src/app/community/volunteers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/companies/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/[slug]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[slug]/review">> = Specific
  const handler = {} as typeof import("../../src/app/companies/[slug]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/[slug]/tour/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[slug]/tour">> = Specific
  const handler = {} as typeof import("../../src/app/companies/[slug]/tour/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../src/app/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../src/app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/copilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/copilot">> = Specific
  const handler = {} as typeof import("../../src/app/copilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cost-of-living/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cost-of-living">> = Specific
  const handler = {} as typeof import("../../src/app/cost-of-living/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cv-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cv-builder">> = Specific
  const handler = {} as typeof import("../../src/app/cv-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ai">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/culture-fit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/culture-fit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/culture-fit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cv">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invite">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mentorship/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mentorship">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mentorship/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/refer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/refer">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/refer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/saved/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/saved">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/saved/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/star-coach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/star-coach">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/star-coach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/ai-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/ai-tools">> = Specific
  const handler = {} as typeof import("../../src/app/employer/ai-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/employer/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/applications">> = Specific
  const handler = {} as typeof import("../../src/app/employer/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/assessments/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/assessments/create">> = Specific
  const handler = {} as typeof import("../../src/app/employer/assessments/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/employer/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/availability">> = Specific
  const handler = {} as typeof import("../../src/app/employer/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/employer/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/candidates">> = Specific
  const handler = {} as typeof import("../../src/app/employer/candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/company-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/company-profile">> = Specific
  const handler = {} as typeof import("../../src/app/employer/company-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/culture-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/culture-profile">> = Specific
  const handler = {} as typeof import("../../src/app/employer/culture-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/cv-parser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/cv-parser">> = Specific
  const handler = {} as typeof import("../../src/app/employer/cv-parser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/cv-search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/cv-search">> = Specific
  const handler = {} as typeof import("../../src/app/employer/cv-search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/emiratization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/emiratization">> = Specific
  const handler = {} as typeof import("../../src/app/employer/emiratization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/events">> = Specific
  const handler = {} as typeof import("../../src/app/employer/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/hiring-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/hiring-assistant">> = Specific
  const handler = {} as typeof import("../../src/app/employer/hiring-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/jobs/[id]/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/jobs/[id]/applications">> = Specific
  const handler = {} as typeof import("../../src/app/employer/jobs/[id]/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/jobs/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/jobs/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/employer/jobs/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/jobs/[id]/share/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/jobs/[id]/share">> = Specific
  const handler = {} as typeof import("../../src/app/employer/jobs/[id]/share/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/employer/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/messages">> = Specific
  const handler = {} as typeof import("../../src/app/employer/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/mohre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/mohre">> = Specific
  const handler = {} as typeof import("../../src/app/employer/mohre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/nafis-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/nafis-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/employer/nafis-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/offers">> = Specific
  const handler = {} as typeof import("../../src/app/employer/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/employer/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer">> = Specific
  const handler = {} as typeof import("../../src/app/employer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/post/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/post">> = Specific
  const handler = {} as typeof import("../../src/app/employer/post/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/profile">> = Specific
  const handler = {} as typeof import("../../src/app/employer/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/scorecards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/scorecards">> = Specific
  const handler = {} as typeof import("../../src/app/employer/scorecards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/search-cvs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/search-cvs">> = Specific
  const handler = {} as typeof import("../../src/app/employer/search-cvs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/talent-pool/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/talent-pool">> = Specific
  const handler = {} as typeof import("../../src/app/employer/talent-pool/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/team">> = Specific
  const handler = {} as typeof import("../../src/app/employer/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/verify">> = Specific
  const handler = {} as typeof import("../../src/app/employer/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/video-interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/video-interviews">> = Specific
  const handler = {} as typeof import("../../src/app/employer/video-interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../src/app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/golden-visa-checker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/golden-visa-checker">> = Specific
  const handler = {} as typeof import("../../src/app/golden-visa-checker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/interview-prep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview-prep">> = Specific
  const handler = {} as typeof import("../../src/app/interview-prep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/interview-questions/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview-questions/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/interview-questions/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/interview/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/interview/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/interview/schedule/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/schedule/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/interview/schedule/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs-in/[emirate]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs-in/[emirate]">> = Specific
  const handler = {} as typeof import("../../src/app/jobs-in/[emirate]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/accommodation-provided-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/accommodation-provided-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/accommodation-provided-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/blue-visa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/blue-visa">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/blue-visa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/emiratization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/emiratization">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/emiratization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/female-jobs-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/female-jobs-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/female-jobs-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/freezone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/freezone">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/freezone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/fresher-jobs-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/fresher-jobs-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/fresher-jobs-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/gulf-jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/gulf-jobs">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/gulf-jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/jobs-for-filipinos-in-dubai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/jobs-for-filipinos-in-dubai">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/jobs-for-filipinos-in-dubai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/jobs-for-indians-in-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/jobs-for-indians-in-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/jobs-for-indians-in-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/jobs-for-pakistanis-in-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/jobs-for-pakistanis-in-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/jobs-for-pakistanis-in-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/part-time-jobs-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/part-time-jobs-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/part-time-jobs-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/remote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/remote">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/remote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/urgent-hiring-uae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/urgent-hiring-uae">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/urgent-hiring-uae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/visa-provided/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/visa-provided">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/visa-provided/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/walk-in-interview-dubai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/walk-in-interview-dubai">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/walk-in-interview-dubai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobseeker/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobseeker/settings">> = Specific
  const handler = {} as typeof import("../../src/app/jobseeker/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/join/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/join/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../src/app/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/market-insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market-insights">> = Specific
  const handler = {} as typeof import("../../src/app/market-insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nafis-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nafis-guide">> = Specific
  const handler = {} as typeof import("../../src/app/nafis-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offer/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offer/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/offer/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/post-a-job/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/post-a-job">> = Specific
  const handler = {} as typeof import("../../src/app/post-a-job/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quick-post/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quick-post">> = Specific
  const handler = {} as typeof import("../../src/app/quick-post/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reference/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reference/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/reference/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/resources/labour-rights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/labour-rights">> = Specific
  const handler = {} as typeof import("../../src/app/resources/labour-rights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/resources/relocation-advisor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/relocation-advisor">> = Specific
  const handler = {} as typeof import("../../src/app/resources/relocation-advisor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/salaries/[role]/[emirate]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salaries/[role]/[emirate]">> = Specific
  const handler = {} as typeof import("../../src/app/salaries/[role]/[emirate]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/salaries/[role]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salaries/[role]">> = Specific
  const handler = {} as typeof import("../../src/app/salaries/[role]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/salaries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salaries">> = Specific
  const handler = {} as typeof import("../../src/app/salaries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/salary-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salary-guide">> = Specific
  const handler = {} as typeof import("../../src/app/salary-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/salary/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salary/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/salary/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/success-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success-stories">> = Specific
  const handler = {} as typeof import("../../src/app/success-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/success-stories/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success-stories/submit">> = Specific
  const handler = {} as typeof import("../../src/app/success-stories/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/swipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/swipe">> = Specific
  const handler = {} as typeof import("../../src/app/swipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/talent/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/talent/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/talent/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/talent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/talent">> = Specific
  const handler = {} as typeof import("../../src/app/talent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/ai-mock-interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/ai-mock-interview">> = Specific
  const handler = {} as typeof import("../../src/app/tools/ai-mock-interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/ai-resume-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/ai-resume-builder">> = Specific
  const handler = {} as typeof import("../../src/app/tools/ai-resume-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/ats-checker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/ats-checker">> = Specific
  const handler = {} as typeof import("../../src/app/tools/ats-checker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/career-transition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/career-transition">> = Specific
  const handler = {} as typeof import("../../src/app/tools/career-transition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/job-scam-checker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/job-scam-checker">> = Specific
  const handler = {} as typeof import("../../src/app/tools/job-scam-checker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/negotiation-simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/negotiation-simulator">> = Specific
  const handler = {} as typeof import("../../src/app/tools/negotiation-simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/salary-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/salary-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/tools/salary-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/salary-comparison/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/salary-comparison">> = Specific
  const handler = {} as typeof import("../../src/app/tools/salary-comparison/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verified-employers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verified-employers">> = Specific
  const handler = {} as typeof import("../../src/app/verified-employers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify/[hash]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/[hash]">> = Specific
  const handler = {} as typeof import("../../src/app/verify/[hash]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/visa-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visa-guide">> = Specific
  const handler = {} as typeof import("../../src/app/visa-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/volunteer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/volunteer">> = Specific
  const handler = {} as typeof import("../../src/app/volunteer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/walk-in-interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/walk-in-interviews">> = Specific
  const handler = {} as typeof import("../../src/app/walk-in-interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/whatsapp-groups/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp-groups/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/whatsapp-groups/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/whatsapp-groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp-groups">> = Specific
  const handler = {} as typeof import("../../src/app/whatsapp-groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wps-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wps-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/wps-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/expire-jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/expire-jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/expire-jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/inbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/inbound">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/inbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[slug]/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[slug]/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[slug]/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/group-cover/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/group-cover">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/group-cover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/hiring/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/hiring">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/hiring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quick-post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quick-post">> = Specific
  const handler = {} as typeof import("../../src/app/api/quick-post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/telegram/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telegram/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/telegram/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/telegram/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telegram/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/telegram/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trpc/[trpc]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trpc/[trpc]">> = Specific
  const handler = {} as typeof import("../../src/app/api/trpc/[trpc]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploadthing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploadthing">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploadthing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/transcribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/job-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/job-import">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/job-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/whapi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/whapi">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/whapi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/s/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/s/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/s/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/employer">> = Specific
  const handler = {} as typeof import("../../src/app/employer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
